name: Merge pull request to main if no merge conflicts

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge pull request into main branch
        run: |
          git merge --no-commit --no-ff "refs/pull/${{ github.event.pull_request.number }}/merge"
      
      - name: Check for merge conflicts
        run: |
          if [[ -n $(git diff --name-only --diff-filter=U) ]]; then
            echo "There is a merge conflict, please resolve it before merging"
            git merge --abort
            exit 1
          else
            echo "No merge conflicts"
          fi
          
      - name: Build with Maven and run tests
        run: mvn clean verify    

      - name: Push changes to main branch
        if: success()
        run: |
          git push origin main
