name: Merge branch into main

on:
  push:
    branches: [ issue/* ]

jobs:
  merge-into-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Merge branch into main
        run: |
          git config user.name 'Github Actions'
          git config user.email '<>'
          git checkout origin/main
          git merge --no-ff "${GITHUB_REF#refs/heads/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to main branch
        run: |
          git fetch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
