name: Merge issue branch to main if no merge conflicts, and build with maven

on:
  push:
    branches:
      - 'issue/*'

jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout issue branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}

      - name: Merge issue branch into main branch
        run: |
          git config user.name 'Github Actions'
          git config user.email '<>'
          git merge --no-ff "${{ github.event.ref }}"

      - name: Check for merge conflicts
        run: |
          if [[ -n $(git diff --name-only --diff-filter=U) ]]; then
            echo "There is a merge conflict, please resolve it before merging"
            git merge --abort
            exit 1
          else
            echo "No merge conflicts"
          fi
        
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Build with Maven and run tests
        run: |
          mvn clean verify

      - name: Push changes to main branch
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Merging branch ${{ github.event.ref }} into main"
          commit_options: "--no-verify"
          branch: main
          file_pattern: ""
          author_name: "Github Actions"
          author_email: "<>"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
